### ISSUE TITLE
DNS Security

### ISSUE THREAD

**Issue by adrelanos** [PrivSec-dev/privsec.dev#136]
Regarding:
https://privsec.dev/posts/linux/desktop-linux-hardening/#dnssec

You might like this wiki page:
https://www.kicksecure.com/wiki/DNS_Security

Missing topics:

* DNSSEC validating vs non-validating
* DNS encryption (DoT, DoH)

**Comment by wj25czxj47bu6q** [comment]
These are actually not missing topics.

The post, as written, addresses DNSSEC validation. Not following the indicated steps would result in a _non-validating_ setup, which is useless for removing trust from your DNS provider. Following the steps results in a _validating_ configuration. Perhaps the wording should be tweaked, but nothing more.

DNS transport encryption has very little real value and isn't worth mentioning. Only in edge-cases does it solve a problem in a proper threat model.

- Privacy from your ISP: Pointless, because your ISP can still see the domains you visit. Use a VPN instead.
- Preventing DNS poisoning: DNSSEC validation is the real solution here. However, even in the absence of DNSSEC, public&#8209;key cryptography (TLS certificates) solves this problem for 99% of websites (and any websites without functional TLS are untrustable even if the DNS hasn't been poisoned).

DNS transport encryption is good for two things:

- Circumventing extremely rudimentary DNS-based censorship
- Removing trust from the ISP with respect to DNS records that are both unprotected by DNSSEC (because the domain registrant has neglected to enable it) and unprotected by any other mechanisms like public&#8209;key cryptography

**Comment by adrelanos** [comment]
> * Privacy from your ISP: Pointless, because your ISP can still see the domains you visit. Use a VPN instead.

> DNS transport encryption is good for two things:
> 
> * Circumventing extremely rudimentary DNS-based censorship.

Encrypted DNS + encrypted hello (`ECH`) (which is underway) (previously encrypted `SNI` (`ESNI`)) will help. If a service is hosted by a popular CDN (cloudflare) then the ISP can neither see DNS nor SNI. Should only know in practice in many cases "something cloudflare". In result, censorship will be difficult. It remains to be seen if `website traffic fingerprinting` would get deployed then.

> * Removing trust from the ISP with respect to DNS records that are both unprotected by DNSSEC (because the domain registrant has neglected to enable it) and unprotected by any other mechanisms like public‑key cryptography. You are still forced to trust your DNS provider of choice.

True. But good for users if they can choose to use their ISP or another DNS provider.

> Missing topics:
> 
> * DNSSEC validating vs non-validating

What I mean by that is that not all DNS resolvers are validating even though "DNSSEC". Examples:

* https://github.com/DNSCrypt/dnscrypt-proxy/discussions/1954
* https://github.com/cloudflare/cloudflared/issues/520

I find that very surprising. Dunno if you consider this worth mentioning.

**Comment by wj25czxj47bu6q** [comment]
ECH is not yet standardized and has no known implementations at this time. We will reconsider this topic once that changes.

And you are correct that not all resolvers support DNSSEC validation. Unbound and systemd-resolved seem like the best choices currently.
